### PR TITLE
Config and looping

### PR DESCRIPTION
**Pull request by Dediggefedde**
.dev file added for devc++ project file. I recommend using wxDevC++.
.h and .rc added for config dialog.
.c changed (dialog added, volume correction).

org-files that Loop will loop the number you set within the
config-dialog. Using 0 means endless. org-files that has no
looping-setting won't loop. winamp will use its shuffle-procedure
afterwards.

I also let org be played at the winamp volume. Before it was
automatically set to full-volume.

Output dll-file is inside \src\Output\MingW\

Maybe it's my lack of understanding how github works, but I guessed
having the actual output dll is also nice... That's why I also changed the .gitignore file regarding .dll-files.

### CODE REVIEW

**Comment by Yukitty** [comment]
When a release tag is created (see [releases](https://github.com/Yukitty/in_org/releases)) you can upload the dll (or zip file containing the dll, readme, etc. as a package) to be provided as a download from that page, therefore uploading it as part of the repository itself is not required.

Perhaps I should make it more obvious by putting something in the readme.md or something though..?

**Comment by Dediggefedde** [comment]
ok, thanks^^
I wasn't aware of the release-feature of Github... I missed any "Release" button so far. ^^
Sometimes I still am oblivious to important features around here. ^^
I changed the .gitignore again... don't know If I have to remove the .dll manually now...

**Comment by Yukitty** [comment]
I did a cherrypick of the commit before you added the dll and committed that as a release, with an updated README.md to match. :) Thank you again!

**Comment by Dediggefedde** [comment]
Thanks^^
I'm still not really used to Github and similar things... until now I used a  freehoster, made some nice little php-scripts for version-control, download-counter, download-overview etc. and presented those things in respective forums.
But I guessed times have changed and currently, those platforms are probably the best way of sharing code-art-pieces that are used on a wider base... sooner or later there sure will be someone trying to make a fork or pull-request. ^^

**Pull request closed without merging**
